// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Task1.Human Health Hospital;



/************************************************************/
/**
 * 
 */
public class Administrator {
				/**
				 * 
				 */
				public String Name;
				/**
				 * 
				 */
				public String ID;
				/**
				 * 
				 */
				public String Gender;
				/**
				 * 
				 */
				public int Age;
	/**
	 * 
	 */
	public void ViewDocAttendance() {
	}
	/**
	 * 
	 */
	public void Inventory() {
	}
}
