// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Task1.Human Health Hospital;



/************************************************************/
/**
 * 
 */
public class Dentist extends Doctor
 {
	/**
	 * 
	 * @param Last_hospital_name 
	 * @param Last_Checkup_Time 
	 * @param Last_Dental_visit 
	 */
	public void Previous_History(String Last_hospital_name, String Last_Checkup_Time, String Last_Dental_visit) {
	}
	/**
	 * 
	 */
	public void Denatal_Cleaner() {
	}
}
