// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Task1.Human Health Hospital;



/************************************************************/
/**
 * 
 */
public class Doctor {
				/**
				 * 
				 */
				public String ID;
				/**
				 * 
				 */
				public String Name;
				/**
				 * 
				 */
				public String Gender;
				/**
				 * 
				 */
				public int Age;
				/**
				 * 
				 */
				public Patient[] patient;
	/**
	 * 
	 */
	public void LogInDoctor () {
	}
	/**
	 * 
	 */
	public void Ring() {
	}
}
