// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Task1.Human

Health Hospital;

/************************************************************/
/**
 * 
 */
public class Eyes Specialist extends Doctor
 {
	/**
	 * 
	 * @param Last_hospital_name 
	 * @param Last_Checkup_Time 
	 * @param Last_eyesight_number 
	 */
	public void Previous_History(String Last_hospital_name, String Last_Checkup_Time, float Last_eyesight_number) {
	}
	/**
	 * 
	 */
	public void Checking() {
	}
}
