// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Task1.Human Health Hospital;



/************************************************************/
/**
 * 
 */
public class Patient {
				/**
				 * 
				 */
				public String ID;
				/**
				 * 
				 */
				public String Name;
				/**
				 * 
				 */
				public int Age;
				/**
				 * 
				 */
				public String Gender;
	/**
	 * 
	 * @param name 
	 * @param Age 
	 * @param Reason 
	 * @param Current_med 
	 */
	public void TokenIssue(String name, int Age, String Reason, String Current_med) {
	}
}
