// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Task1.Human

Health Hospital;

/************************************************************/
/**
 * 
 */
public class Physician extends Doctor {
	/**
	 * 
	 * @param Last_hospital_name 
	 * @param Last_Checkup_Time 
	 * @param Last_Uric_Acid 
	 */
	public void Previous_History(String Last_hospital_name, String Last_Checkup_Time, String Last_Uric_Acid) {
	}

	/**
	 * 
	 */
	public void URIC-ACID-TEST() {
	}
}
