// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Task 2.Car Making Company;



/************************************************************/
/**
 * 
 */
public class Car {
				/**
				 * 
				 */
				public Engine engine;
				/**
				 * 
				 */
				public String Name;
				/**
				 * 
				 */
				public String Manufacturing_Date;
				/**
				 * 
				 */
				public String Color;
				/**
				 * 
				 */
				public String Company_name;
				/**
				 * 
				 */
				public int Seats_no;
				/**
				 * 
				 */
				public undef Property12;
	/**
	 * 
	 * @return 
	 */
	public boolean Has_PowerWIndows() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean Has_Power_Steering() {
	}
	/**
	 * 
	 * @return 
	 */
	public int No_seatters() {
	}
	/**
	 * 
	 * @return 
	 */
	public Engine Engine_type() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean Has_Parachute() {
	}
}
