// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Task 2.Car Making Company;



/************************************************************/
/**
 * 
 */
public class Engine {
				/**
				 * 
				 */
				public int Horse_Power;
				/**
				 * 
				 */
				public String[] Sensors_name;
				/**
				 * 
				 */
				public int Engine_number;
				/**
				 * 
				 */
				public String Manufacturing_date;
	/**
	 * 
	 * @return 
	 */
	public boolean IS_Multipurpose() {
	}
	/**
	 * 
	 * @return 
	 */
	public int No_Horsepower() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean Is_Sensors() {
	}
}
