// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Task

3.D IYA State Agent;

/************************************************************/
/**
 * 
 */
public class House {
	/**
	 * 
	 */
	public int House_no;
	/**
	 * 
	 */
	public String Location;
	/**
	 * 
	 */
	public int Size;
	/**
	 * 
	 */
	public int No_of_Rooms;
	/**
				 * 
				 */
				public House Owner
	house owner;
}
