// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Task

3.D IYA State Agent;

/************************************************************/
/**
 * 
 */
public class House Owner
{
	/**
	 * 
	 */
	public String Name;
	/**
	 * 
	 */
	public String Contact_no;
	/**
	 * 
	 */
	public int Age;
	/**
				 * 
				 */
				public State Agent
	state agent;
}
