// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Task 3.DIYA State Agent;



/************************************************************/
/**
 * 
 */
public class Renter {
				/**
				 * 
				 */
				public String Name;
				/**
				 * 
				 */
				public String Contact_no;
				/**
				 * 
				 */
				public int Age;
}
