// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Task

3.D IYA State Agent;

/************************************************************/
/**
 * 
 */
public class State Agent
{
	/**
	 * 
	 */
	public String Name;
	/**
	 * 
	 */
	public String Contact_no;
	/**
	 * 
	 */
	public int Age;
}
