// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Task 3.DIYA State Agent;



/************************************************************/
/**
 * 
 */
public class Two_Portions extends House
 {
				/**
				 * 
				 */
				public int Monthly_Charge;
	/**
	 * 
	 * @return 
	 */
	public boolean Has_Open_Kitchen() {
	}
	/**
	 * 
	 * @return 
	 */
	public int No_rooms() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean Has_Car_Parking() {
	}
}
