// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Example.Library Management System;



/************************************************************/
/**
 * 
 */
public class Journal {
				/**
				 * 
				 */
				private String Name;
				/**
				 * 
				 */
				private int ID;
				/**
				 * 
				 */
				private String Author;
				/**
				 * 
				 */
				private String Publish;
}
