// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Example.Library Management System;



/************************************************************/
/**
 * 
 */
public class Library {
				/**
				 * 
				 */
				public String Name;
				/**
				 * 
				 */
				public String Phone;
				/**
				 * 
				 */
				public Books books;
				/**
				 * 
				 */
				public Journal journal;
				/**
				 * 
				 */
				public Membership membership;
	/**
	 * 
	 * @return 
	 */
	public String addbook() {
	}
	/**
	 * 
	 * @return 
	 */
	public String Removebook() {
	}
	/**
	 * 
	 * @return 
	 */
	public String addjournal() {
	}
	/**
	 * 
	 * @return 
	 */
	public String removeJournal() {
	}
}
