// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Example.Library Management System;



/************************************************************/
/**
 * 
 */
public class Membership {
				/**
				 * 
				 */
				private int ID;
				/**
				 * 
				 */
				private String Name;
	/**
	 * 
	 */
	public void Issue() {
	}
	/**
	 * 
	 */
	public void Return() {
	}
}
