// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Example.Library Management System;



/************************************************************/
/**
 * 
 */
public class Student extends Membership
 {
				/**
				 * 
				 */
				private int ID;
				/**
				 * 
				 */
				private String Name;
}
